version: 2
jobs:
  lint:
    docker:
      - image: quay.io/cybozu/ubuntu:18.04
    steps:
    - run: apt-get update
    - run: apt-get install -y --no-install-recommends make pylint3 pycodestyle
    - checkout
    - run: make lint PYLINT3=pylint3
  build:
    machine:
      image: circleci/classic:201708-01
    steps:
      - checkout
      - run: sudo apt-get update
      - run: make setup
      - run: cp ./setup/cluster.json.example ./setup/cluster.json
      - run: make cloud iso
      - persist_to_workspace:
          root: build
          paths:
            - cybozu-ubuntu-18.04.1-server-amd64.iso
            - cybozu-ubuntu-18.04-server-cloudimg-amd64.img
  release:
    docker:
      - image: quay.io/cybozu/golang:1.10-bionic
    steps:
      - attach_workspace:
          at: ./artifacts
      - run: ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_TAG} ./artifacts/

workflows:
  version: 2
  main:
    jobs:
      - lint
      - build
  release:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - release:
          requires:
            - lint
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
