#!/bin/sh -e

while true; do
    uuid=$(rkt list --no-legend | awk '{if ($4 == "running" && $2 == "chrony") print $1}')
    if [ "$uuid" != "" ]; then
        break
    fi
done

exec rkt enter --app=chrony $uuid chronyc waitsync 600 0.1 0.0 1
