#!/bin/sh

if [ $# -ne 1 ]; then
  echo "Usage: setup-hw <bmc-address>" 1>&2
  exit 1
fi

bmc=$1; shift

vm=$(systemd-detect-virt -v)

if [ "$vm" != "none" ]; then
  # notify BMC address to placemat
  echo $bmc > /dev/virtio-ports/placemat
fi
