#!/usr/bin/python3

import os
import shutil
import subprocess


def systemctl(*args):
    cmd = ["systemctl"]
    cmd.extend(args)
    subprocess.run(cmd, check=True)


def main():
    shutil.copyfile("/extras/setup/omsa.service", "/etc/systemd/system/omsa.service")
    shutil.copyfile("/extras/setup/setup-hw", "/usr/local/sbin/setup-hw")
    os.chmod("/usr/local/sbin/setup-hw", 0o755)

    systemctl("daemon-reload")
    systemctl("enable", "omsa.service")
    systemctl("start", "omsa.service")


if __name__ == '__main__':
    main()
