#!/usr/bin/python3

import argparse
import getpass
import os
import shutil
import subprocess

ETCD_SNAPSHOT_PASSWORD = '/usr/local/etc/etcd-snapshot.passwd'


def dump_file(name: str, data: str):
    os.makedirs(os.path.dirname(name), 0o755, exist_ok=True)
    with open(name, "w") as f:
        f.write(data)
        f.flush()
        os.fsync(f.fileno())


def systemctl(*args):
    cmd = ["systemctl"]
    cmd.extend(args)
    subprocess.run(cmd, check=True)


def setup_etcd_snapshot(password: str):

    dump_file(ETCD_SNAPSHOT_PASSWORD, password)

    shutil.copyfile("/extras/setup/etcd-snapshot.sh", "/usr/local/bin/etcd-snapshot.sh")
    shutil.copyfile("/extras/setup/etcd-snapshot.service", "/etc/systemd/system/etcd-snapshot.service")
    shutil.copyfile("/extras/setup/etcd-snapshot.timer", "/etc/systemd/system/etcd-snapshot.timer")

    systemctl("daemon-reload")
    systemctl("enable", "etcd-snapshot.timer")
    systemctl("start", "etcd-snapshot.timer")


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--etcd-snapshot-password', dest='password',
                   help='etcd user password (only for GCP env)')

    ns = p.parse_args()
    password = ns.password
    if password is None:
        password = getpass.getpass('etcd backup password: ')

    setup_etcd_snapshot(password)


if __name__ == '__main__':
    main()
